In [19]:
import platform
print(platform.platform())

import tensorflow as tf
print(tf.__version__)

Linux-4.4.59+-x86_64-with-Ubuntu-18.04-bionic
2.0.0


In [20]:
rand = tf.random.uniform([1],0,1)
print(rand)
rand = tf.random.uniform([4],0,1)
print(rand)
rand = tf.random.normal([4],0,1)
print(rand)

tf.Tensor([0.6823361], shape=(1,), dtype=float32)
tf.Tensor([0.6415732  0.06022656 0.8785373  0.6913433 ], shape=(4,), dtype=float32)
tf.Tensor([-0.03335258 -0.38798696 -1.3710227   0.5458356 ], shape=(4,), dtype=float32)


In [21]:
import math
def sigmoid(x):
    return 1 / (1 + math.exp(-x))

In [22]:
# 3.11 뉴런의 입력과 출력 정의
x = 1
y = 0
w = tf.random.normal([1],0,1)
output = sigmoid(x * w)
print(output)

0.41743708926487333


In [23]:
# 3.12 경사 하강법을 이용한 뉴런의 학습
for i in range(1000):
    output = sigmoid(x * w)
    error = y - output
    w = w + x * 0.1 * error
    
    if i % 100 == 99:
        print(i, error, output)

99 -0.09563690490567413 0.09563690490567413
199 -0.05050255360633716 0.05050255360633716
299 -0.03400432675079942 0.03400432675079942
399 -0.02555716133705129 0.02555716133705129
499 -0.020445392799688652 0.020445392799688652
599 -0.01702607372509271 0.01702607372509271
699 -0.014580735457996883 0.014580735457996883
799 -0.012746328350603055 0.012746328350603055
899 -0.011319905380917103 0.011319905380917103
999 -0.010179387066534738 0.010179387066534738


In [24]:
# 3.13 x=0 일 때 y=1 을 얻는 뉴런의 학습
x = 0
y = 1
w = tf.random.normal([1],0,1)

for i in range(1000):
    output = sigmoid(x * w)
    error = y - output
    w = w + x * 0.1 * error
    
    if i % 100 == 99:
        print(i, error, output)

99 0.5 0.5
199 0.5 0.5
299 0.5 0.5
399 0.5 0.5
499 0.5 0.5
599 0.5 0.5
699 0.5 0.5
799 0.5 0.5
899 0.5 0.5
999 0.5 0.5


In [25]:
# 3.14 x=0 일 때 y=1 을 얻는 뉴런의 학습에 편향을 더함
x = 0
y = 1
w = tf.random.normal([1],0,1)
b = tf.random.normal([1],0,1)

for i in range(1000):
    output = sigmoid(x * w + 1 * b)
    error = y - output
    w = w + x * 0.1 * error
    b = b + 1 * 0.1 * error
    
    if i % 100 == 99:
        print(i, error, output)

99 0.09040500194303192 0.9095949980569681
199 0.048938578083359 0.951061421916641
299 0.03327674044321616 0.9667232595567838
399 0.025140604096765773 0.9748593959032342
499 0.020176658432014993 0.979823341567985
599 0.016838692357164176 0.9831613076428358
699 0.014442781476612154 0.9855572185233878
799 0.01264056191466445 0.9873594380853356
899 0.011236309228345509 0.9887636907716545
999 0.010111646678578112 0.9898883533214219


In [26]:
# 3.15 True, False 의 정수값 확인
print(int(True))
print(int(False))

1
0


In [27]:
# 3.16 첫번째 신경망 네트워크 : AND
import numpy as np
x = np.array([[1,1], [1,0], [0,1], [0,0]])
y = np.array([[1], [0], [0], [0]])
w = tf.random.normal([2],0,1)
b = tf.random.normal([1],0,1)
b_x = 1

for i in range(2000):
    error_sum = 0
    for j in range(4):
        output = sigmoid(np.sum(x[j]*w)+b_x*b)
        error = y[j][0] - output
        w = w + x[j] * 0.1 * error
        b = b + b_x * 0.1 * error
        error_sum += error
        
    if i % 200 == 199:
        print(i, error_sum)

199 -0.11219290844922701
399 -0.06636376162197924
599 -0.04701086340761888
799 -0.036291604700209146
999 -0.02949887451346868
1199 -0.024818166971645007
1399 -0.0214032135296459
1599 -0.01880517967283648
1799 -0.016761602035586885
1999 -0.015114938628399287


In [28]:
# 3.17 파이썬에서 리스트에 정수를 곱하기
print([1,2,3]*2)
print([1,2,3]*0)
print([1,2,3]*-1)

[1, 2, 3, 1, 2, 3]
[]
[]


In [29]:
# 3.18 파이썬에서 리스트에 실수를 곱하기
# print([1,2,3]*0.01)

TypeError: can't multiply sequence by non-int of type 'float'

In [30]:
# 3.19 넘파이 array 에 정수, 실수를 곱하기
import numpy as np
print(np.array([1,2,3])*2)
print(np.array([1,2,3])*0)
print(np.array([1,2,3])*-1)
print(np.array([1,2,3])*0.01)

[2 4 6]
[0 0 0]
[-1 -2 -3]
[0.01 0.02 0.03]


In [31]:
# 3.20 AND 네트워크의 평가
for i in range(4):
    print('X:', x[i], 'Y:', y[i], 'Output:', sigmoid(np.sum(x[i]*w)+b))

X: [1 1] Y: [1] Output: 0.9647119032316477
X: [1 0] Y: [0] Output: 0.02500536608142539
X: [0 1] Y: [0] Output: 0.02508223142803273
X: [0 0] Y: [0] Output: 2.4135110588939226e-05


In [32]:
# 3.21 두번째 신경망 네트워크 : OR
import numpy as np
x = np.array([[1,1], [1,0], [0,1], [0,0]])
y = np.array([[1], [1], [1], [0]])
w = tf.random.normal([2],0,1)
b = tf.random.normal([1],0,1)
b_x = 1

for i in range(2000):
    error_sum = 0
    for j in range(4):
        output = sigmoid(np.sum(x[j]*w)+b_x*b)
        error = y[j][0] - output
        w = w + x[j] * 0.1 * error
        b = b + b_x * 0.1 * error
        error_sum += error
        
    if i % 200 == 199:
        print(i, error_sum)

199 -0.045106277654469035
399 -0.024488171987079282
599 -0.01673981907231341
799 -0.012678439686562022
999 -0.010186409803206516
1199 -0.00850483245179913
1399 -0.007295249227830786
1599 -0.006384149303774206
1799 -0.005674280020675378
1999 -0.005104123872069228


In [33]:
# 3.22 OR 네트워크의 평가
for i in range(4):
    print('X:', x[i], 'Y:', y[i], 'Output:', sigmoid(np.sum(x[i]*w)+b))

X: [1 1] Y: [1] Output: 0.9999972794308919
X: [1 0] Y: [1] Output: 0.9898632794344967
X: [0 1] Y: [1] Output: 0.9898721748665975
X: [0 0] Y: [0] Output: 0.025308646835730267


In [35]:
# 3.23 세번째 신경망 네트워크 : XOR
import numpy as np
x = np.array([[1,1], [1,0], [0,1], [0,0]])
y = np.array([[0], [1], [1], [0]])
w = tf.random.normal([2],0,1)
b = tf.random.normal([1],0,1)
b_x = 1

for i in range(2000):
    error_sum = 0
    for j in range(4):
        output = sigmoid(np.sum(x[j]*w)+b_x*b)
        error = y[j][0] - output
        w = w + x[j] * 0.1 * error
        b = b + b_x * 0.1 * error
        error_sum += error
        
    if i % 200 == 199:
        print(i, error_sum)

199 0.002264964074130016
399 9.205257900513075e-05
599 3.7358747346782906e-06
799 1.3588374314643659e-07
999 1.8614211283463078e-09
1199 1.8614210173240053e-09
1399 1.8614210173240053e-09
1599 1.8614210173240053e-09
1799 1.8614210173240053e-09
1999 1.8614210173240053e-09


In [36]:
# 3.24 XOR 네트워크의 평가
for i in range(4):
    print('X:', x[i], 'Y:', y[i], 'Output:', sigmoid(np.sum(x[i]*w)+b))

X: [1 1] Y: [0] Output: 0.5128176323940516
X: [1 0] Y: [1] Output: 0.5128176314633411
X: [0 1] Y: [1] Output: 0.4999999990686774
X: [0 0] Y: [0] Output: 0.49999999813735485
