In [1]:
import platform
print(platform.platform())

import tensorflow as tf
print(tf.__version__)

Linux-4.4.59+-x86_64-with-Ubuntu-18.04-bionic
2.0.0


In [2]:
rand = tf.random.uniform([1],0,1)
print(rand)
rand = tf.random.uniform([4],0,1)
print(rand)
rand = tf.random.normal([4],0,1)
print(rand)

tf.Tensor([0.20760262], shape=(1,), dtype=float32)
tf.Tensor([0.844273   0.72946465 0.4197023  0.8909888 ], shape=(4,), dtype=float32)
tf.Tensor([ 0.017139  -1.1202171  0.5301106  0.8177472], shape=(4,), dtype=float32)


In [3]:
import math
def sigmoid(x):
    return 1 / (1 + math.exp(-x))

In [4]:
# 3.11 뉴런의 입력과 출력 정의
x = 1
y = 0
w = tf.random.normal([1],0,1)
output = sigmoid(x * w)
print(output)

0.08100954180201261


In [5]:
# 3.12 경사 하강법을 이용한 뉴런의 학습
for i in range(1000):
    output = sigmoid(x * w)
    error = y - output
    w = w + x * 0.1 * error
    
    if i % 100 == 99:
        print(i, error, output)

99 -0.04614175979767944 0.04614175979767944
199 -0.0319405687886069 0.0319405687886069
299 -0.02436460173917474 0.02436460173917474
399 -0.01967142938993524 0.01967142938993524
499 -0.01648424747839317 0.01648424747839317
599 -0.014180656276373651 0.014180656276373651
699 -0.01243898827774887 0.01243898827774887
799 -0.011076552040373942 0.011076552040373942
899 -0.009981944342081259 0.009981944342081259
999 -0.009083440556517343 0.009083440556517343


In [7]:
# 3.13 x=0 일 때 y=1 을 얻는 뉴런의 학습
x = 0
y = 1
w = tf.random.normal([1],0,1)

for i in range(1000):
    output = sigmoid(x * w)
    error = y - output
    w = w + x * 0.1 * error
    
    if i % 100 == 99:
        print(i, error, output)

99 0.5 0.5
199 0.5 0.5
299 0.5 0.5
399 0.5 0.5
499 0.5 0.5
599 0.5 0.5
699 0.5 0.5
799 0.5 0.5
899 0.5 0.5
999 0.5 0.5


In [8]:
# 3.14 x=0 일 때 y=1 을 얻는 뉴런의 학습에 편향을 더함
x = 0
y = 1
w = tf.random.normal([1],0,1)
b = tf.random.normal([1],0,1)

for i in range(1000):
    output = sigmoid(x * w + 1 * b)
    error = y - output
    w = w + x * 0.1 * error
    b = b + 1 * 0.1 * error
    
    if i % 100 == 99:
        print(i, error, output)

99 0.10958253290666986 0.8904174670933301
199 0.05435000001148804 0.945649999988512
299 0.035737880921979825 0.9642621190780202
399 0.026532845922579207 0.9734671540774208
499 0.021068381679894888 0.9789316183201051
599 0.017457421535932216 0.9825425784640678
699 0.014896725031731117 0.9851032749682689
799 0.012987606416125508 0.9870123935838745
899 0.0115101019983741 0.9884898980016259
999 0.010333091031408337 0.9896669089685917


In [9]:
# 3.15 True, False 의 정수값 확인
print(int(True))
print(int(False))

1
0
