In [1]:
import platform
print(platform.platform())

import tensorflow as tf
print(tf.__version__)

Linux-4.4.59+-x86_64-with-Ubuntu-18.04-bionic
2.0.0


In [2]:
rand = tf.random.uniform([1],0,1)
print(rand)
rand = tf.random.uniform([4],0,1)
print(rand)
rand = tf.random.normal([4],0,1)
print(rand)

tf.Tensor([0.20760262], shape=(1,), dtype=float32)
tf.Tensor([0.844273   0.72946465 0.4197023  0.8909888 ], shape=(4,), dtype=float32)
tf.Tensor([ 0.017139  -1.1202171  0.5301106  0.8177472], shape=(4,), dtype=float32)


In [3]:
import math
def sigmoid(x):
    return 1 / (1 + math.exp(-x))

In [4]:
# 3.11 뉴런의 입력과 출력 정의
x = 1
y = 0
w = tf.random.normal([1],0,1)
output = sigmoid(x * w)
print(output)

0.08100954180201261


In [5]:
# 3.12 경사 하강법을 이용한 뉴런의 학습
for i in range(1000):
    output = sigmoid(x * w)
    error = y - output
    w = w + x * 0.1 * error
    
    if i % 100 == 99:
        print(i, error, output)

99 -0.04614175979767944 0.04614175979767944
199 -0.0319405687886069 0.0319405687886069
299 -0.02436460173917474 0.02436460173917474
399 -0.01967142938993524 0.01967142938993524
499 -0.01648424747839317 0.01648424747839317
599 -0.014180656276373651 0.014180656276373651
699 -0.01243898827774887 0.01243898827774887
799 -0.011076552040373942 0.011076552040373942
899 -0.009981944342081259 0.009981944342081259
999 -0.009083440556517343 0.009083440556517343


In [7]:
# 3.13 x=0 일 때 y=1 을 얻는 뉴런의 학습
x = 0
y = 1
w = tf.random.normal([1],0,1)

for i in range(1000):
    output = sigmoid(x * w)
    error = y - output
    w = w + x * 0.1 * error
    
    if i % 100 == 99:
        print(i, error, output)

99 0.5 0.5
199 0.5 0.5
299 0.5 0.5
399 0.5 0.5
499 0.5 0.5
599 0.5 0.5
699 0.5 0.5
799 0.5 0.5
899 0.5 0.5
999 0.5 0.5


In [8]:
# 3.14 x=0 일 때 y=1 을 얻는 뉴런의 학습에 편향을 더함
x = 0
y = 1
w = tf.random.normal([1],0,1)
b = tf.random.normal([1],0,1)

for i in range(1000):
    output = sigmoid(x * w + 1 * b)
    error = y - output
    w = w + x * 0.1 * error
    b = b + 1 * 0.1 * error
    
    if i % 100 == 99:
        print(i, error, output)

99 0.10958253290666986 0.8904174670933301
199 0.05435000001148804 0.945649999988512
299 0.035737880921979825 0.9642621190780202
399 0.026532845922579207 0.9734671540774208
499 0.021068381679894888 0.9789316183201051
599 0.017457421535932216 0.9825425784640678
699 0.014896725031731117 0.9851032749682689
799 0.012987606416125508 0.9870123935838745
899 0.0115101019983741 0.9884898980016259
999 0.010333091031408337 0.9896669089685917


In [9]:
# 3.15 True, False 의 정수값 확인
print(int(True))
print(int(False))

1
0


In [10]:
# 3.16 첫번째 신경망 네트워크 : AND
import numpy as np
x = np.array([[1,1], [1,0], [0,1], [0,0]])
y = np.array([[1], [0], [0], [0]])
w = tf.random.normal([2],0,1)
b = tf.random.normal([1],0,1)
b_x = 1

for i in range(2000):
    error_sum = 0
    for j in range(4):
        output = sigmoid(np.sum(x[j]*w)+b_x*b)
        error = y[j][0] - output
        w = w + x[j] * 0.1 * error
        b = b + b_x * 0.1 * error
        error_sum += error
        
    if i % 200 == 199:
        print(i, error_sum)

199 -0.10235426809930537
399 -0.06280844588954392
599 -0.04517638730089037
799 -0.03517554417752886
999 -0.02875054698832628
1199 -0.0242836052892662
1399 -0.021002724023855987
1599 -0.01849318829058225
1799 -0.016514460406546642
1999 -0.014913180723078371


In [2]:
# 3.17 파이썬에서 리스트에 정수를 곱하기
print([1,2,3]*2)
print([1,2,3]*0)
print([1,2,3]*-1)

[1, 2, 3, 1, 2, 3]
[]
[]


In [11]:
# 3.18 파이썬에서 리스트에 실수를 곱하기
print([1,2,3]*0.01)

TypeError: can't multiply sequence by non-int of type 'float'

In [12]:
# 3.19 넘파이 array 에 정수, 실수를 곱하기
import numpy as np
print(np.array([1,2,3])*2)
print(np.array([1,2,3])*0)
print(np.array([1,2,3])*-1)
print(np.array([1,2,3])*0.01)

[2 4 6]
[0 0 0]
[-1 -2 -3]
[0.01 0.02 0.03]


In [13]:
# 3.20 AND 네트워크의 평가
for i in range(4):
    print('X:', x[i], 'Y:', y[i], 'Output:', sigmoid(np.sum(x[i]*w)+b))

X: [1 1] Y: [1] Output: 0.9651857651576546
X: [1 0] Y: [0] Output: 0.02467281173493674
X: [0 1] Y: [0] Output: 0.024747817610596995
X: [0 0] Y: [0] Output: 2.3153890413797382e-05


In [14]:
# 3.21 두번째 신경망 네트워크 : OR
import numpy as np
x = np.array([[1,1], [1,0], [0,1], [0,0]])
y = np.array([[1], [1], [1], [0]])
w = tf.random.normal([2],0,1)
b = tf.random.normal([1],0,1)
b_x = 1

for i in range(2000):
    error_sum = 0
    for j in range(4):
        output = sigmoid(np.sum(x[j]*w)+b_x*b)
        error = y[j][0] - output
        w = w + x[j] * 0.1 * error
        b = b + b_x * 0.1 * error
        error_sum += error
        
    if i % 200 == 199:
        print(i, error_sum)

199 -0.05181867854091646
399 -0.0265140187364519
599 -0.017689960494844392
799 -0.013224234235224758
999 -0.010538628398548362
1199 -0.008750279625324105
1399 -0.0074759650683648635
1599 -0.006522756462595321
1799 -0.005783566031108942
1999 -0.005192648194256553


In [16]:
# 3.22 OR 네트워크의 평가
for i in range(4):
    print('X:', x[i], 'Y:', y[i], 'Output:', sigmoid(np.sum(x[i]*w)+b))

X: [1 1] Y: [1] Output: 0.9999971345767832
X: [1 0] Y: [1] Output: 0.9897064926049183
X: [0 1] Y: [1] Output: 0.9896809481096922
X: [0 0] Y: [0] Output: 0.025743170569263306


In [17]:
# 3.23 세번째 신경망 네트워크 : XOR
import numpy as np
x = np.array([[1,1], [1,0], [0,1], [0,0]])
y = np.array([[0], [1], [1], [0]])
w = tf.random.normal([2],0,1)
b = tf.random.normal([1],0,1)
b_x = 1

for i in range(2000):
    error_sum = 0
    for j in range(4):
        output = sigmoid(np.sum(x[j]*w)+b_x*b)
        error = y[j][0] - output
        w = w + x[j] * 0.1 * error
        b = b + b_x * 0.1 * error
        error_sum += error
        
    if i % 200 == 199:
        print(i, error_sum)

199 -0.00508763852284444
399 -0.00020686283853244003
599 -8.410817891935096e-06
799 -3.573928256672687e-07
999 3.722842367714918e-09
1199 3.722842145670313e-09
1399 3.722842145670313e-09
1599 3.722842145670313e-09
1799 3.722842145670313e-09
1999 3.722842145670313e-09


In [1]:
# 3.24 XOR 네트워크의 평가
for i in range(4):
    print('X:', x[i], 'Y:', y[i], 'Output:', sigmoid(np.sum(x[i]*w)+b))

NameError: name 'x' is not defined