In [1]:
import platform
print(platform.platform())

import tensorflow as tf
print(tf.__version__)

Linux-4.4.59+-x86_64-with-Ubuntu-18.04-bionic
2.0.0


In [2]:
rand = tf.random.uniform([1],0,1)
print(rand)
rand = tf.random.uniform([4],0,1)
print(rand)
rand = tf.random.normal([4],0,1)
print(rand)

tf.Tensor([0.20760262], shape=(1,), dtype=float32)
tf.Tensor([0.844273   0.72946465 0.4197023  0.8909888 ], shape=(4,), dtype=float32)
tf.Tensor([ 0.017139  -1.1202171  0.5301106  0.8177472], shape=(4,), dtype=float32)


In [3]:
import math
def sigmoid(x):
    return 1 / (1 + math.exp(-x))

In [4]:
# 3.11 뉴런의 입력과 출력 정의
x = 1
y = 0
w = tf.random.normal([1],0,1)
output = sigmoid(x * w)
print(output)

0.08100954180201261
