In [3]:
import platform
print(platform.platform())

import tensorflow as tf
print(tf.__version__)

Linux-4.4.59+-x86_64-with-Ubuntu-18.04-bionic
2.0.0


In [4]:
rand = tf.random.uniform([1],0,1)
print(rand)
rand = tf.random.uniform([4],0,1)
print(rand)
rand = tf.random.normal([4],0,1)
print(rand)

tf.Tensor([0.4484079], shape=(1,), dtype=float32)
tf.Tensor([0.93157256 0.7241032  0.74604225 0.7179514 ], shape=(4,), dtype=float32)
tf.Tensor([ 0.8829009   0.21164769  1.1252137  -2.03052   ], shape=(4,), dtype=float32)


In [5]:
import math
def sigmoid(x):
    return 1 / (1 + math.exp(-x))

In [6]:
# 3.11 뉴런의 입력과 출력 정의
x = 1
y = 0
w = tf.random.normal([1],0,1)
output = sigmoid(x * w)
print(output)

0.36871806637115645


In [7]:
# 3.12 경사 하강법을 이용한 뉴런의 학습
for i in range(1000):
    output = sigmoid(x * w)
    error = y - output
    w = w + x * 0.1 * error
    
    if i % 100 == 99:
        print(i, error, output)

99 -0.09153520356935792 0.09153520356935792
199 -0.049282534464536225 0.049282534464536225
299 -0.033437889976873324 0.033437889976873324
399 -0.025233216637275617 0.025233216637275617
499 -0.02023653987088677 0.02023653987088677
599 -0.0168805110531538 0.0168805110531538
699 -0.014473574224890384 0.014473574224890384
799 -0.012664174607913845 0.012664174607913845
899 -0.011255004230821585 0.011255004230821585
999 -0.010126811736071377 0.010126811736071377


In [8]:
# 3.13 x=0 일 때 y=1 을 얻는 뉴런의 학습
x = 0
y = 1
w = tf.random.normal([1],0,1)

for i in range(1000):
    output = sigmoid(x * w)
    error = y - output
    w = w + x * 0.1 * error
    
    if i % 100 == 99:
        print(i, error, output)

99 0.5 0.5
199 0.5 0.5
299 0.5 0.5
399 0.5 0.5
499 0.5 0.5
599 0.5 0.5
699 0.5 0.5
799 0.5 0.5
899 0.5 0.5
999 0.5 0.5


In [9]:
# 3.14 x=0 일 때 y=1 을 얻는 뉴런의 학습에 편향을 더함
x = 0
y = 1
w = tf.random.normal([1],0,1)
b = tf.random.normal([1],0,1)

for i in range(1000):
    output = sigmoid(x * w + 1 * b)
    error = y - output
    w = w + x * 0.1 * error
    b = b + 1 * 0.1 * error
    
    if i % 100 == 99:
        print(i, error, output)

99 0.10995976032710819 0.8900402396728918
199 0.05444813816671168 0.9455518618332883
299 0.035781081479486776 0.9642189185205132
399 0.02655689149599383 0.9734431085040062
499 0.021083645361246517 0.9789163546387535
599 0.017467934691981157 0.9825320653080188
699 0.014904382229843027 0.985095617770157
799 0.012993408496523307 0.9870065915034767
899 0.011514676400647628 0.9884853235993524
999 0.010336768400336926 0.9896632315996631


In [10]:
# 3.15 True, False 의 정수값 확인
print(int(True))
print(int(False))

1
0


In [11]:
# 3.16 첫번째 신경망 네트워크 : AND
import numpy as np
x = np.array([[1,1], [1,0], [0,1], [0,0]])
y = np.array([[1], [0], [0], [0]])
w = tf.random.normal([2],0,1)
b = tf.random.normal([1],0,1)
b_x = 1

for i in range(2000):
    error_sum = 0
    for j in range(4):
        output = sigmoid(np.sum(x[j]*w)+b_x*b)
        error = y[j][0] - output
        w = w + x[j] * 0.1 * error
        b = b + b_x * 0.1 * error
        error_sum += error
        
    if i % 200 == 199:
        print(i, error_sum)

199 -0.09695546187752256
399 -0.06073359230242077
599 -0.04407831322045265
799 -0.03449951687237378
999 -0.028293534037763565
1199 -0.023954068803304095
1399 -0.020754841005386597
1599 -0.018300090361425554
1799 -0.016360058611608514
1999 -0.014787172024334622


In [12]:
# 3.17 파이썬에서 리스트에 정수를 곱하기
print([1,2,3]*2)
print([1,2,3]*0)
print([1,2,3]*-1)

[1, 2, 3, 1, 2, 3]
[]
[]


In [13]:
# 3.18 파이썬에서 리스트에 실수를 곱하기
# print([1,2,3]*0.01)

In [14]:
# 3.19 넘파이 array 에 정수, 실수를 곱하기
import numpy as np
print(np.array([1,2,3])*2)
print(np.array([1,2,3])*0)
print(np.array([1,2,3])*-1)
print(np.array([1,2,3])*0.01)

[2 4 6]
[0 0 0]
[-1 -2 -3]
[0.01 0.02 0.03]


In [15]:
# 3.20 AND 네트워크의 평가
for i in range(4):
    print('X:', x[i], 'Y:', y[i], 'Output:', sigmoid(np.sum(x[i]*w)+b))

X: [1 1] Y: [1] Output: 0.9654808778868247
X: [1 0] Y: [0] Output: 0.02446556088011716
X: [0 1] Y: [0] Output: 0.024539233463918054
X: [0 0] Y: [0] Output: 2.2556412387937118e-05


In [16]:
# 3.21 두번째 신경망 네트워크 : OR
import numpy as np
x = np.array([[1,1], [1,0], [0,1], [0,0]])
y = np.array([[1], [1], [1], [0]])
w = tf.random.normal([2],0,1)
b = tf.random.normal([1],0,1)
b_x = 1

for i in range(2000):
    error_sum = 0
    for j in range(4):
        output = sigmoid(np.sum(x[j]*w)+b_x*b)
        error = y[j][0] - output
        w = w + x[j] * 0.1 * error
        b = b + b_x * 0.1 * error
        error_sum += error
        
    if i % 200 == 199:
        print(i, error_sum)

199 -0.05408462317245302
399 -0.027106602282075953
599 -0.017957535667555313
799 -0.013375102571279898
999 -0.010634944559211774
1199 -0.008816820000079065
1399 -0.007524770405265863
1599 -0.006559974209926649
1799 -0.005812840086402805
1999 -0.005216401405334602


In [17]:
# 3.22 OR 네트워크의 평가
for i in range(4):
    print('X:', x[i], 'Y:', y[i], 'Output:', sigmoid(np.sum(x[i]*w)+b))

X: [1 1] Y: [1] Output: 0.9999970949133011
X: [1 0] Y: [1] Output: 0.9896539006876007
X: [0 1] Y: [1] Output: 0.9896403482365771
X: [0 0] Y: [0] Output: 0.025859580700461657


In [18]:
# 3.23 세번째 신경망 네트워크 : XOR
import numpy as np
x = np.array([[1,1], [1,0], [0,1], [0,0]])
y = np.array([[0], [1], [1], [0]])
w = tf.random.normal([2],0,1)
b = tf.random.normal([1],0,1)
b_x = 1

for i in range(2000):
    error_sum = 0
    for j in range(4):
        output = sigmoid(np.sum(x[j]*w)+b_x*b)
        error = y[j][0] - output
        w = w + x[j] * 0.1 * error
        b = b + b_x * 0.1 * error
        error_sum += error
        
    if i % 200 == 199:
        print(i, error_sum)

199 -0.0006287301593027594
399 -2.5571154885439817e-05
599 -1.0396034710868918e-06
799 -4.653552321265408e-09
999 3.722842145670313e-09
1199 3.722842145670313e-09
1399 3.722842145670313e-09
1599 3.722842145670313e-09
1799 3.722842145670313e-09
1999 3.722842145670313e-09


In [19]:
# 3.24 XOR 네트워크의 평가
for i in range(4):
    print('X:', x[i], 'Y:', y[i], 'Output:', sigmoid(np.sum(x[i]*w)+b))
    
# 3.25 XOR 네트워크의 w, b 값 확인
print('w:', w)
print('b:', b)

X: [1 1] Y: [0] Output: 0.5128176286712095
X: [1 0] Y: [1] Output: 0.5128176305326305
X: [0 1] Y: [1] Output: 0.4999999990686774
X: [0 0] Y: [0] Output: 0.5000000009313226
w: tf.Tensor([ 5.1281754e-02 -7.4505806e-09], shape=(2,), dtype=float32)
b: tf.Tensor([3.7252903e-09], shape=(1,), dtype=float32)


In [20]:
# 3.26 AND 네트워크의 w, b 값 확인
# w: tf.Tensor([6.9484286 6.951607 ], shape=(2,), dtype=float32)
# b: tf.Tensor([-10.601849], shape=(1,), dtype=float32)

# 3.27 tf.keras 를 이용한 XOR 네트워크 계산
import numpy as np
x = np.array([[1,1], [1,0], [0,1], [0,0]])
y = np.array([[0], [1], [1], [0]])

model = tf.keras.Sequential([
    tf.keras.layers.Dense(units=2, activation='sigmoid', input_shape=(2,)),
    tf.keras.layers.Dense(units=1, activation='sigmoid')
])

model.compile(optimizer=tf.keras.optimizers.SGD(lr=0.3), loss='mse')

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 2)                 6         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 3         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________
