In [2]:
# https://nicholastsmith.wordpress.com/2016/04/19/stock-market-prediction-using-multi-layer-perceptrons-with-tensorflow/
# https://www.udacity.com/course/machine-learning-for-trading--ud501

import platform
print(platform.platform())

import tensorflow as tf
print(tf.__version__)

Linux-4.4.59+-x86_64-with-Ubuntu-18.04-bionic
2.0.0


In [5]:
rand = tf.random.uniform([1],0,1)
print(rand)
rand = tf.random.uniform([4],0,1)
print(rand)
rand = tf.random.normal([4],0,1)
print(rand)

tf.Tensor([0.38052022], shape=(1,), dtype=float32)
tf.Tensor([0.98332655 0.02605939 0.7225205  0.5997021 ], shape=(4,), dtype=float32)
tf.Tensor([ 0.6026606   0.03330253  1.257041   -0.74198854], shape=(4,), dtype=float32)


In [7]:
import math
def sigmoid(x):
    return 1 / (1 + math.exp(-x))